// Run with: node games/malatang-250g/physics.test.cjs
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const nodes = new Map();
function element() { return { textContent: '', innerHTML: '', hidden: false, disabled: false, children: [], style: { setProperty() {} }, classList: { toggle() {}, add() {}, remove() {} }, parentElement: { classList: { toggle() {}, remove() {} } }, setPointerCapture(id) { this.capture=id; }, hasPointerCapture(id) { return this.capture===id; }, releasePointerCapture() { this.capture=null; }, getBoundingClientRect() { return {left:0,top:0,width:540,height:570}; }, setAttribute() {}, append(x) { this.children.push(x); }, addEventListener() {}, getContext() { return {}; }, focus() {}, scrollIntoView() {} }; }
const context = vm.createContext({ window: { addEventListener() {} }, document: { addEventListener() {}, getElementById(id) { if (!nodes.has(id)) nodes.set(id, element()); return nodes.get(id); }, createElement: element }, localStorage: { getItem() { return null; }, setItem() {} }, Image: class {}, requestAnimationFrame() {}, Math, console, navigator: {} });
const source = fs.readFileSync(__dirname + '/index.html', 'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
vm.runInContext(source, context);
const run = code => vm.runInContext(code, context);
run('begin(); selected=3; drop();');
assert.equal(run('bodies.length'), 1);
run('drop()');
assert.equal(run('bodies.length'), 1, 'rapid duplicate drops should be ignored');
run('for(let i=0;i<1200;i++)step(1/120)');
assert.ok(run('bodies[0].y > 440 && bodies[0].y < 480'), 'meatball should rest on bowl floor');
assert.ok(run('Math.abs(bodies[0].vy)<5'), 'resting body should settle');
run('begin(); for(let n=0;n<32;n++){selected=n%8;dropX=92+(n*73)%356;drop();for(let i=0;i<90;i++)step(1/120)} for(let i=0;i<600;i++)step(1/120)');
assert.equal(run('bodies.length'), 32);
assert.ok(run('bodies.every(b=>Number.isFinite(b.x+b.y+b.a)&&b.x>0&&b.x<540&&b.y<545)'), 'mixed food pile must stay finite and on the table');
run('clock+=1;drop()');
assert.equal(run('bodies.length'), 32, 'capacity must be enforced');
run('begin();selected=3;drop();bodies[0].g=250;bodies[0].y=450;$("weigh").onclick()');
assert.equal(run('mode'), 'result');
assert.equal(run('best'), 0);
assert.ok(nodes.get('result-title').textContent.includes('ぴったり'));
run('clock+=1;drop()');
assert.equal(run('bodies.length'), 1, 'result screen must block drops');
run('begin()');
assert.equal(run('bodies.length'), 0);
assert.equal(run('mode'), 'play');
run("const event=(x,y,id=1)=>({clientX:x,clientY:y,pointerId:id,button:0,preventDefault(){}});const card=$('ingredients').children[3];startDrag(event(620,100),3,card);moveDrag(event(270,150));finishDrag(event(270,150));");
assert.equal(run('bodies.length'),1,'drag into bowl must add one item');
assert.equal(run('bodies[0].y'),150,'drop should start at the release position');
assert.equal(run('drag'),null);
run('clock+=1;startDrag(event(620,100),3,card);moveDrag(event(610,300));finishDrag(event(610,300));');
assert.equal(run('bodies.length'),1,'outside drop must cancel');

run('startDrag(event(270,100),3,card);finishDrag(event(270,100));');
assert.equal(run('bodies.length'),1,'a tap must not drop a food');
run('startDrag(event(620,100,2),3,card);moveDrag(event(270,150,2));cancelDrag();');
assert.equal(run('bodies.length'),1,'cancelled touch must not add food');
assert.equal(run('ghost.hidden'),true);
run('startDrag(event(620,100,3),3,card);moveDrag(event(270,150,3));finishDrag(event(270,150,3));');
assert.equal(run('bodies.length'),2);
assert.ok(run('bodies[1].y<bodies[0].y'),'dropping onto another item should avoid embedded spawn');
run('begin();startDrag(event(620,100),3,card);moveDrag(event(38,400));finishDrag(event(38,400));for(let n=0;n<1200;n++)step(1/120);');
assert.equal(run('bodies.length'),1,'outside bowl placement must be retained');
assert.ok(run('bodies[0].y>500&&bodies[0].y<545'),'outside item must rest on table');
assert.equal(run('bowlWeight()'),0,'outside items must not be weighed');
run('clock+=1;dropX=270;drop();for(let n=0;n<1200;n++)step(1/120)');
assert.equal(run('bowlWeight()'),run('bodies[1].g'),'only inside bowl weight counts');
assert.ok(run('foods[0].w>foods[2].w&&foods[7].w>foods[2].w&&foods[3].w<foods[5].w&&foods[1].w<foods[5].w'));
run('begin();clock=9;updateChef()');
assert.equal(run('chefPhase'),'question');
assert.ok(!nodes.get('chef-speech').textContent.includes('答え'));
run('clock=16;updateChef()');
assert.equal(run('quizIndex'),1);
run('begin();selected=3;dropX=35;drop(400);for(let n=0;n<240;n++){step(1/120);updateChef()}');
assert.equal(run('chefPhase'),'angry');
assert.equal(run('scoldCount'),1);
run("chefImage={name:'normal'};chefAngryImage={name:'angry'}");
assert.equal(run('currentChefImage().name'),'angry');
run('for(let n=0;n<600;n++){step(1/120);updateChef()}');
assert.equal(run('scoldCount'),1,'one spill must not trigger repeated scolding');
assert.notEqual(run('chefPhase'),'angry','quiz must resume after scolding');
assert.equal(run('currentChefImage().name'),'normal');
run('begin();selected=3;dropX=270;drop();for(let n=0;n<600;n++){step(1/120);updateChef()}');
assert.equal(run('scoldCount'),0,'normal bowl drops must not trigger anger');
console.log('PASS: physics, scoring, drag/drop, outside placement, chef quiz/answer, spill reaction, quiz resume');
